<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\NotificationService.Application\NotificationService.Application.csproj" />
    <ProjectReference Include="..\NotificationService.Domain\NotificationService.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Communication.CallAutomation" Version="1.6.0" />
    <PackageReference Include="Azure.Communication.Email" Version="1.1.0" />
    <PackageReference Include="Azure.Data.Tables" Version="12.12.0" />
    <PackageReference Include="Azure.Storage.Blobs" Version="12.29.2" />
    <PackageReference Include="MailKit" Version="4.17.0" />
    <PackageReference Include="MassTransit" Version="8.5.7" />
    <PackageReference Include="MassTransit.Azure.ServiceBus.Core" Version="8.5.7" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.10" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="NotificationService.Tests" />
  </ItemGroup>

</Project>
